require 'packages'
--require 'pairing-config'
require 'config'
require 'treesitter-config'
require 'keybindings'
require 'lsp'
require 'bufferline_config'
require 'lualine-config'
require 'telescope-config'
require 'colorscheme'
require 'format_config'
require 'toggleterm-config'
require 'whichkey-config'
-- require 'git_int_config'
